"""Bilingual (Thai/English) labels สำหรับ ThaiEDA.

ตัวเลือกภาษาเริ่มต้นคือภาษาไทย เพราะเครื่องมือนี้ออกแบบมาเพื่อผู้ใช้ไทยเป็นหลัก
"""

from __future__ import annotations

# ภาษาเริ่มต้น (global) — เปลี่ยนได้ด้วย set_language()
_DEFAULT_LANGUAGE = "th"
_current_language = _DEFAULT_LANGUAGE

# พจนานุกรม label ทั้งหมดที่รายงานต้องใช้
LABELS: dict[str, dict[str, str]] = {
    # --- หัวข้อหลัก ---
    "report_title": {"en": "ThaiEDA Profile Report", "th": "รายงานวิเคราะห์ข้อมูล ThaiEDA"},
    "overview": {"en": "Overview", "th": "ภาพรวม"},
    "quality_issues": {"en": "Data Quality Issues", "th": "ปัญหาคุณภาพข้อมูล"},
    "column_details": {"en": "Column Details", "th": "รายละเอียดคอลัมน์"},
    "generated_by": {"en": "Generated by", "th": "สร้างโดย"},
    # --- ภาพรวม ---
    "rows": {"en": "Rows", "th": "จำนวนแถว"},
    "columns": {"en": "Columns", "th": "จำนวนคอลัมน์"},
    "missing_cells": {"en": "Missing Cells", "th": "เซลล์ที่ว่าง"},
    "missing_pct": {"en": "Missing (%)", "th": "ว่าง (%)"},
    "duplicate_rows": {"en": "Duplicate Rows", "th": "แถวซ้ำ"},
    "total_cells": {"en": "Total Cells", "th": "เซลล์ทั้งหมด"},
    "column_types": {"en": "Column Types", "th": "ประเภทคอลัมน์"},
    # --- ประเภทคอลัมน์ ---
    "type_numeric": {"en": "Numeric", "th": "ตัวเลข"},
    "type_categorical": {"en": "Categorical", "th": "หมวดหมู่"},
    "type_thai_text": {"en": "Thai Text", "th": "ข้อความภาษาไทย"},
    "type_english_text": {"en": "English Text", "th": "ข้อความภาษาอังกฤษ"},
    "type_mixed_text": {"en": "Mixed Text", "th": "ข้อความผสม"},
    "type_datetime": {"en": "Datetime", "th": "วันที่/เวลา"},
    "type_id": {"en": "Identifier", "th": "ตัวระบุ (ID)"},
    "type_empty": {"en": "Empty", "th": "ว่างเปล่า"},
    # --- ความรุนแรง ---
    "severity_critical": {"en": "Critical", "th": "วิกฤต"},
    "severity_warning": {"en": "Warning", "th": "เตือน"},
    "severity_info": {"en": "Info", "th": "ข้อมูล"},
    # --- รายละเอียดปัญหา ---
    "check": {"en": "Check", "th": "การตรวจสอบ"},
    "column": {"en": "Column", "th": "คอลัมน์"},
    "count": {"en": "Count", "th": "จำนวน"},
    "percentage": {"en": "Percentage", "th": "ร้อยละ"},
    "examples": {"en": "Examples", "th": "ตัวอย่าง"},
    "suggestion": {"en": "Suggestion", "th": "ข้อเสนอแนะ"},
    "no_issues": {"en": "No data quality issues detected.", "th": "ไม่พบปัญหาคุณภาพข้อมูล"},
    # --- text metrics ---
    "text_metrics": {"en": "Text Metrics", "th": "สถิติข้อความ"},
    "avg_char_length": {"en": "Avg. Characters", "th": "จำนวนอักขระเฉลี่ย"},
    "avg_token_length": {"en": "Avg. Tokens", "th": "จำนวนคำเฉลี่ย"},
    "median_char_length": {"en": "Median Characters", "th": "จำนวนอักขระมัธยฐาน"},
    "min_char_length": {"en": "Min Characters", "th": "อักขระน้อยสุด"},
    "max_char_length": {"en": "Max Characters", "th": "อักขระมากสุด"},
    "total_tokens": {"en": "Total Tokens", "th": "คำทั้งหมด"},
    "unique_tokens": {"en": "Unique Tokens", "th": "คำไม่ซ้ำ"},
    "top_tokens": {"en": "Top Tokens", "th": "คำที่พบบ่อย"},
    "top_bigrams": {"en": "Top Bigrams", "th": "คู่คำที่พบบ่อย"},
    "top_trigrams": {"en": "Top Trigrams", "th": "สามคำที่พบบ่อย"},
    "wordcloud": {"en": "Word Cloud", "th": "เมฆคำ"},
    "length_distribution": {"en": "Length Distribution", "th": "การกระจายความยาว"},
    "engine_used": {"en": "Tokenizer Engine", "th": "เครื่องมือตัดคำ"},
    "sampled_note": {"en": "Sampled", "th": "สุ่มตัวอย่าง"},
    "of": {"en": "of", "th": "จาก"},
    # --- สถิติพื้นฐาน ---
    "basic_stats": {"en": "Basic Statistics", "th": "สถิติพื้นฐาน"},
    "non_null": {"en": "Non-null", "th": "ไม่ว่าง"},
    "unique": {"en": "Unique", "th": "ไม่ซ้ำ"},
    "mean": {"en": "Mean", "th": "ค่าเฉลี่ย"},
    "std": {"en": "Std. Dev.", "th": "ส่วนเบี่ยงเบนมาตรฐาน"},
    "min": {"en": "Min", "th": "ต่ำสุด"},
    "max": {"en": "Max", "th": "สูงสุด"},
    "top_values": {"en": "Top Values", "th": "ค่าที่พบบ่อย"},
    "more_columns_note": {
        "en": "For deeper numeric/categorical profiling, see ydata-profiling.",
        "th": "สำหรับการวิเคราะห์ตัวเลข/หมวดหมู่เชิงลึก แนะนำ ydata-profiling",
    },
}


def label(key: str, lang: str | None = None) -> str:
    """คืนค่า label ตาม key และภาษา (ถ้าไม่ระบุภาษา ใช้ภาษาปัจจุบัน).

    หากไม่พบ key หรือภาษา จะคืนค่า key เดิมเพื่อให้ระบบไม่ล่ม
    """
    use_lang = lang if lang is not None else _current_language
    entry = LABELS.get(key)
    if entry is None:
        return key
    return entry.get(use_lang) or entry.get("en") or key


def set_language(lang: str) -> None:
    """ตั้งค่าภาษาเริ่มต้นแบบ global (รองรับ 'th' หรือ 'en')."""
    global _current_language
    if lang not in ("th", "en"):
        raise ValueError(f"Unsupported language {lang!r}; expected 'th' or 'en'.")
    _current_language = lang


def get_language() -> str:
    """คืนค่าภาษาปัจจุบัน."""
    return _current_language


__all__ = ["LABELS", "label", "set_language", "get_language"]
